version: "3"

services:
  backend:
    container_name: nextjs-hasura-trello-clone-backend
    image: nextjs-hasura-trello-clone-backend
    build:
      context: .
    depends_on:
      - db
    env_file: ./.env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    restart: on-failure

  db:
    container_name: nextjs-hasura-trello-clone-db
    image: postgres:11.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
